name: Build LaTeX document
on: 
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        latex: [xelatex, lualatex]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Github Action for LaTeX dtx to cls
        uses: FengChendian/latex-dtx2cls-action@4.0.1
        with:
          root_file: njuthesis.dtx
          working_directory: ./

      - name: Compile to PDF
        uses: HermitSun/latex-action@v3
        with:
          root_file: njuthesis-sample.tex
          latexmk_use_${{ matrix.latex }}: true
          args: "-bibtex"

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: PDF_${{ matrix.latex }}
          path: |
            njuthesis-sample.pdf
            njuthesis.cls
            README_EN.md

  release:
    needs: build_latex
    runs-on: ubuntu-latest
    strategy:
      matrix:
        latex: [xelatex]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: PDF_xelatex

      - name: Set Version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Compile to PDF
        uses: HermitSun/latex-action@v3
        with:
          root_file: njuthesis.dtx
          latexmk_use_${{ matrix.latex }}: true
          args: "-bibtex"
          pre_compile: "xetex njuthesis.dtx"
          post_compile: "mv njuthesis.pdf njuthesis-$VERSION.pdf"
      
      - name: Zip Release Source
        run: |
          zip -r njuthesis-$VERSION.zip .vscode chapters/ latexmkrc conf.txsprofile LICENSE Makefile njuthesis.bib njuthesis.cls njuthesis-sample.tex njuvisual.sty README.md

      - name: Zip CTAN Source
        run: |
          mkdir -p njuthesis/
          cp njuthesis-$VERSION.pdf njuthesis/njuthesis.pdf
          cp README-ctan.md njuthesis/README.md
          cp LICENSE njuthesis.dtx njuvisual.dtx njuthesis.ins njuthesis/
          zip -r njuthesis-ctan-$VERSION.zip njuthesis/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            njuthesis-v*.pdf
            njuthesis-v*.zip
            njuthesis-ctan-v*.zip
