name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  CTAN_URL: https://mirrors.rit.edu/CTAN
  TL_PACKAGES: alphalph auxhook biber biblatex biblatex-gb7714-2015 bigfoot blindtext booktabs caption cleveref cm-unicode csquotes ctex dashundergaps emptypage enumitem fancyhdr fancyvrb fandol footmisc hologo hycolor hypdoc hyperref l3build latexmk libertinus-fonts listings lua-ul lualatex-math luatex85 makecell makeindex mathtools newcomputermodern ninecolors njuvisual ntheorem pict2e preview psnfss setspace siunitx standalone symbol tabularray tex-gyre tex-gyre-math threeparttable translator underscore unicode-math xits xstring zhlipsum zref

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/v')"
    env:
      SET_PATH: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install TeX Live
        run: |
          ${{ env.SET_PATH }}
          wget ${{ env.CTAN_URL }}/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -xzf install-tl-unx.tar.gz
          cd install-tl-20* && ./install-tl --profile ../.github/workflows/texlive.profile
          tlmgr install ${{ env.TL_PACKAGES }}
          tlmgr update --self --all --no-auto-install --repository=${{ env.CTAN_URL }}/systems/texlive/tlnet/

      - name: Install latest njuthesis
        run: |
          ${{ env.SET_PATH }}
          l3build install

      - name: Compile test file
        run: |
          ${{ env.SET_PATH }}
          cd test
          latexmk -xelatex  -halt-on-error test-xetex-undergraduate
          xelatex           -halt-on-error test-xetex-graduate
          xelatex           -halt-on-error test-xetex-graduate-nlcover
          latexmk -lualatex -halt-on-error test-luatex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: generated-pdf
          path:
            test/*.pdf
